export default [
  {
    value: "0",
    label: "Quarto de empregada",
    description: "",
    commute: 0,
    rent: 2250,
    bills: 250,
    internet: 250,
    percent: 0.2,
  },
  {
    value: "1",
    label: "Quarto de dormir e home-office",
    description: "",
    commute: 0,
    rent: 2250,
    bills: 350,
    internet: 250,
    percent: 0.15,
  },
  {
    value: "2",
    label: "Quarto só para home-office",
    description: "",
    commute: 0,
    rent: 2500,
    bills: 350,
    internet: 250,
    percent: 0.3,
  },
  {
    value: "3",
    label: "Sala comercial compartilhada",
    description: "",
    commute: 10,
    rent: 1000,
    bills: 0,
    internet: 150,
    percent: 1,
  },
  {
    value: "4",
    label: "Sala comercial própria",
    description: "",
    commute: 10,
    rent: 2500,
    bills: 250,
    internet: 250,
    percent: 1,
  },
  {
    value: "5",
    label: "Alocado no cliente",
    description: "",
    commute: 10,
    rent: 0,
    bills: 0,
    internet: 0,
    percent: 0,
  },
];
